name: Release Charts

on:
  push:
    branches: ["main"]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
          
      - name: Move charts
        run: |
          find ./charts/wildduck -maxdepth 1 -type f -delete
          mv ./charts/wildduck/wildduck/* ./charts/wildduck
          rm -r ./charts/wildduck/wildduck
          
          find ./charts/7dtd -maxdepth 1 -type f -delete
          mv ./charts/7dtd/7dtd/* ./charts/7dtd
          rm -r ./charts/7dtd/7dtd

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.1.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
